import { Request, Response } from 'express';
import PDFDocument from 'pdfkit';
import Issue from '../models/Issue';

export async function generateIssueReport(req: Request, res: Response) {
  try {
    const issue = await Issue.findById(req.params.id).populate('reportedBy', 'name');
    if (!issue) return res.status(404).json({ error: 'Issue not found' });

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=civicsense-report-${issue._id}.pdf`);
    doc.pipe(res);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text('CivicSense AI', 50, 50);
    doc.fontSize(11).font('Helvetica').fillColor('#666').text('Community Hero · Hyperlocal Problem Solver', 50, 75);
    doc.moveTo(50, 95).lineTo(545, 95).strokeColor('#e0e0e0').stroke();

    // Title block
    doc.moveDown(1);
    doc.fontSize(16).font('Helvetica-Bold').fillColor('#000').text(issue.title);
    doc.moveDown(0.3);

    const sevColor = { Critical: '#A32D2D', High: '#BA7517', Medium: '#185FA5', Low: '#3B6D11' }[issue.severity] || '#000';
    doc.fontSize(11).font('Helvetica-Bold').fillColor(sevColor).text(`Severity: ${issue.severity}  |  Priority Score: ${issue.priorityScore}/100`);
    doc.fillColor('#000');
    doc.moveDown(0.5);

    // Key fields
    const fields = [
      ['Category', issue.category],
      ['Department', issue.department],
      ['Status', issue.status.toUpperCase()],
      ['Location', `${issue.location.address}${issue.location.ward ? ', ' + issue.location.ward : ''}, ${issue.location.city}`],
      ['Coordinates', `${issue.location.coordinates[1].toFixed(5)}, ${issue.location.coordinates[0].toFixed(5)}`],
      ['Reported by', (issue.reportedBy as any)?.name || 'Anonymous'],
      ['Reported on', new Date(issue.createdAt).toLocaleDateString('en-IN', { dateStyle: 'long' })],
      ['Community votes', issue.votes.length.toString()],
      ['Verified by', `${issue.verifiedBy.length} community member${issue.verifiedBy.length !== 1 ? 's' : ''}`],
      ['Est. resolution', `${issue.aiAnalysis?.estimatedFixDays || '?'} working days`],
    ];

    doc.moveDown(0.5);
    fields.forEach(([label, value]) => {
      doc.fontSize(10).font('Helvetica-Bold').text(`${label}: `, { continued: true });
      doc.font('Helvetica').text(value || '—');
    });

    // Description
    doc.moveDown(1);
    doc.fontSize(12).font('Helvetica-Bold').text('Issue Description');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').text(issue.description, { lineGap: 4 });

    // AI Recommendation
    if (issue.aiAnalysis) {
      doc.moveDown(1);
      doc.fontSize(12).font('Helvetica-Bold').text('AI Action Recommendation');
      doc.moveDown(0.3);
      doc.fontSize(10).font('Helvetica').fillColor('#333').text(
        `Assigned to ${issue.aiAnalysis.suggestedDepartment} with ${Math.round((issue.aiAnalysis.confidence || 0) * 100)}% AI confidence. Estimated ${issue.aiAnalysis.estimatedFixDays} days to resolve.`
      );
    }

    // Footer
    doc.fillColor('#000');
    const pageBottom = doc.page.height - 60;
    doc.fontSize(9).fillColor('#999')
      .text(`Generated by CivicSense AI · ${new Date().toLocaleString('en-IN')} · Report ID: ${issue._id}`, 50, pageBottom, { align: 'center', width: 495 });

    doc.end();
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Report generation failed' });
  }
}
